// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using eShop.Sellers.API.Infrastructure;

#nullable disable

namespace eShop.Sellers.API.Infrastructure.Migrations
{
    [DbContext(typeof(SellersContext))]
    [Migration("20260916190445_AddSellerPayouts")]
    partial class AddSellerPayouts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("eShop.Sellers.API.Model.Seller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("BankAccountInfo")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("bank_account_info");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("commission_rate");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("SellerId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("sellers", null, t =>
                        {
                            t.HasCheckConstraint("CK_sellers_commission_rate_range", "commission_rate >= 0 AND commission_rate <= 1");

                            t.HasCheckConstraint("CK_sellers_status_valid", "status IN ('Active', 'Inactive', 'Suspended')");
                        });
                });

            modelBuilder.Entity("eShop.Sellers.API.Model.SellerPayout", b =>
                {
                    b.Property<Guid>("PayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("payout_id");

                    b.Property<decimal>("CommissionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("commission_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("GrossAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("gross_amount");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<int>("OrderLineItemId")
                        .HasColumnType("integer")
                        .HasColumnName("order_line_item_id");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<decimal>("SellerAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("seller_amount");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("PayoutId");

                    b.HasIndex("OrderId", "OrderLineItemId")
                        .IsUnique();

                    b.HasIndex("SellerId", "CreatedAt");

                    b.ToTable("seller_payouts", null, t =>
                        {
                            t.HasCheckConstraint("CK_seller_payouts_amounts_non_negative", "gross_amount >= 0 AND commission_amount >= 0 AND seller_amount >= 0");

                            t.HasCheckConstraint("CK_seller_payouts_amounts_reconcile", "gross_amount = commission_amount + seller_amount");

                            t.HasCheckConstraint("CK_seller_payouts_status_valid", "status IN ('Pending', 'Processed', 'Paid')");
                        });
                });

            modelBuilder.Entity("eShop.Sellers.API.Model.SellerPayout", b =>
                {
                    b.HasOne("eShop.Sellers.API.Model.Seller", "Seller")
                        .WithMany("Payouts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("eShop.Sellers.API.Model.Seller", b =>
                {
                    b.Navigation("Payouts");
                });
#pragma warning restore 612, 618
        }
    }
}
